services:
    yourowncard:
        container_name: your-own-card
        ports:
            - 5000:5000 # <Host Port>:<Container Port (do not change)>
        image: your-own-card
        volumes:
            - ./protected/profiles:/app/protected/profiles
            - ./static/profiles:/app/static/profiles
            - ./config.ini:/app/config.ini
        restart: unless-stopped